### ISSUE TITLE
page 102 error of vectored interrupts

### ISSUE THREAD

**Issue by lizhm82** [Lingrui98/RISC-V-book#12]
侧边栏中关于向量中断所设置的寄存器，应该是mtvec，而不是mtval。

**Comment by Lingrui98** [comment]
原书pdf中确实是mtval，见rvbook.pdf中第124页（书中页码为104）

**Comment by lizhm82** [comment]
那应该是原书笔误吧，mtval确实是不正确的

**Comment by Lingrui98** [comment]
> 那应该是原书笔误吧，mtval确实是不正确的

最近得知原书的作者把这个地方修复了，因此这里也一并更新。感谢您！
