### ISSUE TITLE
page 103 error of timer interrupt

### ISSUE THREAD

**Issue by LoveZJT** [Lingrui98/RISC-V-book#19]
> 当 hart 的时间比较器（一个名为 mtimecmp 的内存映射寄存器）大于实时计数器
mtime 时，会触发时钟中断。

这个地方应该是笔误吧，在riscv-privileged-v1.10.pdf中，是这样的：

>Platforms provide a 64-bit memory-mapped machine-mode timer compare register (mtimecmp), which causes a timer interrupt to be posted when the mtime register contains a value greater than or equal to the value in the mtimecmp register.

所以这里应该是mtime≥mtimecmp才会引发时钟中断。

**Comment by LoveZJT** [comment]
page 110：补充说明

> 由于 Sv39 的虚拟地址比 RV64 整数寄存器要短，可能你想知道剩下的 35 位是什么。

这里应该是剩下的25位吧。

**Comment by LoveZJT** [comment]
page 134，前面两条指令我猜应该是csrs和csrsi吧。指令的说明也有点对不上。

**Comment by Lingrui98** [comment]
时钟中断的问题也存在于本书的英文原版中，已根据另一版riscv-manual中的内容修正；
附录中的问题是校对的疏忽，已改正。
谢谢您！
