### ISSUE TITLE
typo: the type of instruction ori is not R-type

### ISSUE THREAD

**Issue by marryjianjian** [Lingrui98/RISC-V-book#23]
https://github.com/Lingrui98/RISC-V-book/blob/b53e4fd7296548428dc3d22d503aa9c0c4187bf3/md%20version/Appendix%20A.md?plain=1#L2064

The type of instruction ori should be I-type not R-type.

**Comment by Lingrui98** [comment]
Thanks! We are currently working on a newer version of the book, and this error will be fixed then

**Comment by Lingrui98** [comment]
New version has been uploaded

**Comment by Lingrui98** [comment]
New version has been uploaded
