### ISSUE TITLE
typo: ld 应该为 RV64I Only

### ISSUE THREAD

**Issue by unlsycn** [Lingrui98/RISC-V-book#26]
https://github.com/Lingrui98/RISC-V-book/blob/b53e4fd7296548428dc3d22d503aa9c0c4187bf3/md%20version/Appendix%20A.md?plain=1#L1848

`ld`是`RV64I Only`指令

**Comment by Lingrui98** [comment]
感谢指出问题！我们会在新构建的版本统一进行修正！
