### ISSUE TITLE
图10.1和图10.2颠倒

### ISSUE THREAD

**Issue by moremorefaito** [Lingrui98/RISC-V-book#32]
当我发现"图 10.1 是 RISC-V 特权指令的图形表示"中的图10.1是机器指令码的时候, 我很困惑.
我阅读了英文版本比对, 然后发现中文版本的图10.1和10.2颠倒了.
此外, 可能这里翻译成"图示"更合适些.
谢谢!

**Comment by Lingrui98** [comment]
确实存在此问题，不过原版已不再维护，我们已在最新发布的第二版翻译中修复 : )
